vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        user_image:
            uri_prefix: /user
            upload_destination: user.storage # Use the name you defined for your storage here
    metadata:
        type: attribute

<<<<<<< ours
=======
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
>>>>>>> theirs
