networks:
  internal:
    internal: true
  exposed:
    internal: false

secrets:
  database-password:
    file: portfolio/secrets/DATABASE_PASSWORD

services:
  web:
    build:
      context: .
      dockerfile: build/Dockerfile
      target: dev
    secrets:
      - source: database-password
        target: database-password
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/var/www/html:rw
    ports:
      - ${PORTFOLIO_BLOG_PORT}:8080
    networks:
      - internal
      - exposed

  database:
    image: docker.io/library/mysql:8-oracle
    environment:
      MYSQL_DATABASE: 'mydbname'
      MYSQL_USER: 'qadadain'
      MYSQL_PASSWORD_FILE: '/run/secrets/database-password'
      MYSQL_ONETIME_PASSWORD: yes
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    secrets:
      - database-password
    networks:
      - internal

  dbadmin:
    image: docker.io/library/phpmyadmin:5.1-apache
    environment:
      PMA_USER: 'qadadain'
      PMA_PASSWORD_FILE: '/run/secrets/database-password'
      PMA_HOST: 'database'
    secrets:
      - database-password
    networks:
      - internal
      - exposed
    ports:
      - '8080:80'