# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

    #config/packages/fos_ckeditor.yaml
fos_ck_editor:
    #par défault le path démarre au dossier /public
    base_path: "bundles/ckeditor_mybuild"
    js_path:   "bundles/ckeditor_mybuild/ckeditor.js"

