vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        user_image:
            uri_prefix: /user
            upload_destination: user.storage # Use the name you defined for your storage here
    metadata:
        type: attribute

